Pull Request for Desktop version portfolio
Tarto-4/Desktop_Portfolio pull request #1
Opened 2023-05-12 14:13 UTC by Tarto-4

# Changes
Linter configuration.
Added animations
Add media quarries in CSS file

*To add animation and transition, media quarries*

2023-05-12 15:41 UTC, NahnahAJ requested changes
## Project Status: CHANGES REQUIRED :recycle: 
Hi @Tarto-4 , 

Good job so far!
There are some issues that you still need to work on to go to the next project but you are almost there!
<img src="https://media0.giphy.com/media/VlqzeaRnhCvPLfrSh6/giphy.gif"/>

## Highlights
- No linter errors :heavy_check_mark: 
- Good use of GitHub Flow :heavy_check_mark: 
- Professional Pull request :heavy_check_mark: 

## Required Changes ♻️
_Check the comments under the review._

## Optional suggestions
_Every comment with the [OPTIONAL] prefix is not crucial enough to stop the approval of this PR. However, I strongly recommend you take them into account as they can make your code better._

You can also consider:
- N/A

Cheers, and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me in your question so I can receive the notification.

**_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561) you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

2023-05-12 15:41 UTC, nahnahdev commented on index.html
> +</button>
- [x] Great job so far @Tarto-4 You've done a good job with this project. There are just a few changes that need to be made and you'll be n your way to the next project :wink: 
- [x] It looks like throughout your project, most of your images have broken links. Which is making your project not look exactly like that of the Figma design :+1: 
- [x] In your navbar, this image isn't showing so please fix it :+1: 
- Your Design
![image](https://github.com/Tarto-4/Desktop_Portfolio/assets/102699958/0f3f1f58-819b-4a70-8a66-18a4b56dec3c)

- The Figma Design 
![image](https://github.com/Tarto-4/Desktop_Portfolio/assets/102699958/de9a4637-ae3d-49f0-956c-06cff5a198c0)

2023-05-12 15:41 UTC, nahnahdev commented on index.html
> +
- [x] In the headline section, you are currently missing the background image as seen in the Figma design. Kindly add it and ensure that it is well positioned as in the Figma design :100: 
- [x] Secondly, from the screenshot below, you can see that all the `social icons` are currently broken so kindly fix those as well :wink: 
- Your Design
![image](https://github.com/Tarto-4/Desktop_Portfolio/assets/102699958/a66ad4c9-33f0-4205-bdef-00b778d1178d)

- The Figma Design
![image](https://github.com/Tarto-4/Desktop_Portfolio/assets/102699958/4c5c30f6-1c15-4fc4-a39c-f24c069b4d5a)

2023-05-12 15:41 UTC, nahnahdev commented on index.html
> +
- [x] In the works section, two of the image links are broken. I have indicated them in the screenshot below so kindly fix those as well :+1: 
- Your Design
![image](https://github.com/Tarto-4/Desktop_Portfolio/assets/102699958/6d13462d-6116-4427-a25e-33b7cbfdca8a)

- The Figma Design
![image](https://github.com/Tarto-4/Desktop_Portfolio/assets/102699958/0379a9ea-dc95-4357-8b3e-111b30761f1f)

2023-05-12 15:41 UTC, NahnahAJ commented on index.html
> +                    Hello I’m a software developer! I can help you build a product , feature or website Look through some of my work and experience! If you like what you see and have a project you ne
- [ ] In the `About section` you're missing the background image seen in the Figma design :+1: I will suggest that you fix that as well :wink: 
- Your Design
![image](https://github.com/Tarto-4/Desktop_Portfolio/assets/102699958/981883b1-7b62-478d-bedb-b700e70c1a74)

- The Figma Design
![image](https://github.com/Tarto-4/Desktop_Portfolio/assets/102699958/138d2154-ebdd-4a29-9540-e0e28aa0672a)

2023-05-12 15:41 UTC, NahnahAJ commented on index.html
> +                    <img src="img/framework-icon.svg" alt="rectangle icon" />
- [ ] The images for each of the categories are also currently broken so kindly fix that as well :wink: 
- Your Design
![image](https://github.com/Tarto-4/Desktop_Portfolio/assets/102699958/5089db2a-69d6-4dab-b396-308a8af011ac)

- The Figma Design
![image](https://github.com/Tarto-4/Desktop_Portfolio/assets/102699958/1a962a24-57a2-43ee-af81-d8aa6f0fda03)

2023-05-12 15:41 UTC, NahnahAJ commented on index.html
> +        </div>
- [ ] Lastly, the `social icons ` in the footer section are also currently not showing. So kindly fix that as well :100: 
- Your Design
![image](https://github.com/Tarto-4/Desktop_Portfolio/assets/102699958/5183fd96-746d-4f3c-913c-8d854919b184)

- The Figma Design
![image](https://github.com/Tarto-4/Desktop_Portfolio/assets/102699958/ca467b57-aff1-4cf4-97a0-9b15405374ce)

2023-05-12 15:41 UTC, NahnahAJ commented on index.html
> +                    Hello I’m a software developer! I can help you build a product , feature or website Look through some of my work and experience! If you like what you see and have a project you ne
- [ ] In the mobile view, I noticed that your `About section` looks different than how it was before and how it is in the Figma design. SO kidly fix that as well :wink:

| Your Design | The Figma Design |
|--------|--------|
| ![image](https://github.com/Tarto-4/Desktop_Portfolio/assets/102699958/009723d7-0ff6-4118-a1f9-6028bd9ee12c) | ![image](https://github.com/Tarto-4/Desktop_Portfolio/assets/102699958/c29cf05a-8f5b-4edc-bb7f-4e6902b1e6a4) |

2023-05-12 15:41 UTC, NahnahAJ commented on index.html
> +            <div class="headline-img-box"></div>
- [ ] In the headline section of the mobile view, you're also missing the background image as seen in the Figma design. So kindly fix this as well :+1: 
- [ ] Lastly, in the mobile view please ensure that there are no broken image links when on mobile view as well :wink: 

| Your Design | The Figma Design |
|--------|--------|
|![image](https://github.com/Tarto-4/Desktop_Portfolio/assets/102699958/3d82ee3e-0506-4181-90ac-b2a2653d9f91) | ![image](https://github.com/Tarto-4/Desktop_Portfolio/assets/102699958/357a1db3-a203-4536-bbeb-fd86d8ccb1a6) |

2023-05-13 06:53 UTC, emmiiorji approved these changes
Hi @Tarto-4, 

# Status: Approved ✅

Your project is complete!  There is nothing else to say other than... it's time to merge it :shipit: 
Congratulations! 🎉 

<div align='center'>
<img src='https://user-images.githubusercontent.com/20554583/220871050-9893fe6a-46a0-42a3-8a44-46ac0f7f1154.gif'/>
</div>

## Good Highlights✔️

- Images now render as expected

Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me in your question so I can receive the notification.

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561)  you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

2023-05-13 06:56 UTC, merged